export const GET_INVESTEDFUNDS = "GET_INVESTEDFUNDS";
export const GET_DATAFUND = "GET_DATAFUND";
export const GET_DATACALL = "GET_DATACALL";
export const GET_DATACOMMITMENT = "GET_DATACOMMITMENT";
export const ADD_NEW_CALL_INV = "ADD_NEW_CALL_INV";
export const UPDATE_INV_STATUS = "UPDATE_INV_STATUS";
export const LOAD_CALL_VALUES = "LOAD_CALL_VALUES";
