# Generated by Django 3.0.7 on 2020-06-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCall',
            fields=[
                ('call_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('investment_name', models.CharField(max_length=255)),
                ('capital_requiement', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DataCommitment',
            fields=[
                ('commitment_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fund_id', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='DataFund',
            fields=[
                ('fund_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataFundInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.IntegerField(default=0)),
                ('commitment_id', models.IntegerField(default=0)),
                ('fund_id', models.IntegerField(default=0)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
